FROM python:3.6.14-buster
WORKDIR /workspace
RUN pip install -r requirements.txt asgiref beautifulsoup4 certifi chardet dj-database-url Django django-bootstrap4 django-crispy-forms django-filter django-heroku gunicorn idna importlib-metadata psycopg2 pytz requests soupsieve sqlparse typing-extensions urllib3 whitenoise zipp
